### ISSUE TITLE
Default alignment compression factor?

### ISSUE THREAD

**Issue by kaspermunch** [CshlSiepelLab/argweaver#1]
Hi Melissa,

I came across this error running arg-sample:

error: unable to compress sequences at given compression level (--compress-seq)

but when I explicitly set the --compress-seq 1, which the help text says is the default value, it runs fine (but slowly). I assume 1 is not really the default value. Can you tell me what is it is and what may make arg-sample unable to compress at a certain level?

Thanks,
Kasper Munch

**Comment by mjhubisz** [comment]
Hi Kasper,
The default is indeed 1. Are you saying you got the "unable to compress sequences" messages when you didn't specify a compression level at all? Are you sure you didn't use -c? 

The error message usually happens when compression is set too high, and should never happen with c=1 .  The compression algorithm will not compress two variant sites together, so if the density of variant sites is too high you will see this error.

Can you send me the command you are using that is producing the error?

**Comment by kaspermunch** [comment]
Hi Melissa,

Thanks a lot. The -c options is was used too. So it makes total sense. I was relaying the question from a student and did not do my due diligence. Sorry for the inconvenience, and thanks for the explanation of how the error arises.

Cheers,
Kasper
On 25 May 2020, 16.46 +0200, Melissa J Hubisz <notifications@github.com>, wrote:

Hi Kasper,
The default is indeed 1. Are you saying you got the "unable to compress sequences" messages when you didn't specify a compression level at all? Are you sure you didn't use -c?

The error message usually happens when compression is set too high, and should never happen with c=1 . The compression algorithm will not compress two variant sites together, so if the density of variant sites is too high you will see this error.

Can you send me the command you are using that is producing the error?

**Comment by mjhubisz** [comment]
Glad it's working! Thanks for following up.
